In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
x=np.array([5,15,25,35,45,55]).reshape(-1,1)
y=np.array([5,20,14,32,22,38])

In [6]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [3]:
y

array([ 5, 20, 14, 32, 22, 38])

In [11]:
#create model and fit
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [12]:
model=LinearRegression().fit(x,y)

In [13]:
r_sq=model.score(x,y)
print(f"coefficient of determination:{r_sq}")
print(f"intercept:{model.intercept_}")
print(f"slope:{model.coef_}")

coefficient of determination:0.7158756137479542
intercept:5.633333333333329
slope:[0.54]


In [14]:
y_pred=model.predict(x)
print(f"predicted response:/n{y_pred}")

predicted response:/n[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [29]:
print(model.intercept_+model.coef_*x)
print(f"predicted response:/n{y_pred}")
print(f"predicted response:/n[8.33...]")

[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]
predicted response:/n[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
predicted response:/n[8.33...]
